name: Flipt
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: wget -qO- https://get.flipt.io/v2 | sh -s -- v2.2.0
      - run: flipt validate
