# yaml-language-server: $schema=https://raw.githubusercontent.com/flipt-io/flipt/v2/config/flipt.schema.json
analytics:
  storage:
    prometheus:
      enabled: true
      url: http://prometheus:9090
      headers:
        Authorization: ${env:PROMETHEUS_AUTH_TOKEN}

authentication:
  required: false

authorization:
  required: false

credentials:
  gitea:
    type: basic
    basic:
      username: admin
      password: password

environments:
  onoffinc:
    default: true
    name: "onoffinc"
    storage: "onoffinc"
#    scm:
#      type: gitea
#      api_url: http://gitea.docker.localhost:3000/
#      credentials: gitea

storage:
  onoffinc:
    remote: "http://ogit:8080/onoffinc-features.git"
    branch: "main"
    poll_interval: "30s"
    fetch_policy: "lenient"
    backend:
      type: memory
